apiVersion: v1
kind: Service
metadata:
  name: simple-html-website-service
spec:
  selector:
    app: simple-html-website
  ports:
  - port: 80
    name: "nginx-app"
    targetPort: 80
    nodePort: 30081
    protocol: TCP
  type: NodePort
